[package]
name = "yapre_io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yapre-graphics-core = { path = "../graphics-core" }
pk_stl = "0.1.0"
